In [10]:
import pandas as pd
import glob
import os

In [32]:
data = {}

for file in files:
    name = os.path.basename(file).replace(".csv", "")
    data[name] = pd.read_csv(file)
    
len(data)

35

In [30]:
data.keys()

dict_keys(['Cities', 'Conferences', 'MConferenceTourneyGames', 'MGameCities', 'MMasseyOrdinals', 'MNCAATourneyCompactResults', 'MNCAATourneyDetailedResults', 'MNCAATourneySeedRoundSlots', 'MNCAATourneySeeds', 'MNCAATourneySlots', 'MRegularSeasonCompactResults', 'MRegularSeasonDetailedResults', 'MSeasons', 'MSecondaryTourneyCompactResults', 'MSecondaryTourneyTeams', 'MTeamCoaches', 'MTeamConferences', 'MTeams', 'MTeamSpellings', 'SampleSubmissionStage1', 'SampleSubmissionStage2', 'WConferenceTourneyGames', 'WGameCities', 'WNCAATourneyCompactResults', 'WNCAATourneyDetailedResults', 'WNCAATourneySeeds', 'WNCAATourneySlots', 'WRegularSeasonCompactResults', 'WRegularSeasonDetailedResults', 'WSeasons', 'WSecondaryTourneyCompactResults', 'WSecondaryTourneyTeams', 'WTeamConferences', 'WTeams', 'WTeamSpellings'])

In [31]:
data['Cities']

     CityID                   City State
0      4001                Abilene    TX
1      4002                  Akron    OH
2      4003                 Albany    NY
3      4004            Albuquerque    NM
4      4005              Allentown    PA
..      ...                    ...   ...
504    4527       Colorado Springs    CO
505    4528                Hershey    PA
506    4529  Charlotte Amalie West    VI
507    4530       Puerto Aventuras    MX
508    4531                 Odessa    TX

[509 rows x 3 columns]

In [33]:
data['Cities'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 509 entries, 0 to 508
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CityID  509 non-null    int64
 1   City    509 non-null    object
 2   State   509 non-null    object
dtypes: int64(1), object(2)
memory usage: 12.1+ KB

In [34]:
data['Cities'].shape

(509, 3)

In [35]:
data['Cities'].columns

Index(['CityID', 'City', 'State'], dtype='object')

In [36]:
data['Conferences'].head()

  ConfAbbrev                   Description
0      a_sun       Atlantic Sun Conference
1      a_ten        Atlantic 10 Conference
2        aac  American Athletic Conference
3        acc     Atlantic Coast Conference
4        aec       America East Conference

In [37]:
data['Conferences'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ConfAbbrev   51 non-null     object
 1   Description  51 non-null     object
dtypes: object(2)
memory usage: 948.0+ bytes

In [38]:
data['Conferences'].shape

(51, 2)

In [45]:
data['MConferenceTourneyGames']

      Season ConfAbbrev  DayNum  WTeamID  LTeamID
0       2001        ovc     120     1122     1369
1       2001        ovc     120     1183     1287
2       2001        ovc     120     1293     1398
3       2001        ovc     120     1399     1404
4       2001      a_sun     121     1194     1144
...      ...        ...     ...      ...      ...
6788    2025        sec     132     1196     1397
6789    2025        aac     132     1272     1412
6790    2025    big_ten     132     1276     1458
6791    2025      a_ten     132     1433     1206
6792    2025        ivy     132     1463     1165

[6793 rows x 5 columns]

In [40]:
data['MConferenceTourneyGames'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6793 entries, 0 to 6792
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Season      6793 non-null   int64
 1   ConfAbbrev  6793 non-null   object
 2   DayNum      6793 non-null   int64
 3   WTeamID     6793 non-null   int64
 4   LTeamID     6793 non-null   int64
dtypes: int64(4), object(1)
memory usage: 265.5+ KB

In [43]:
data['MConferenceTourneyGames']['ConfAbbrev'].unique()

array(['ovc', 'a_sun', 'southern', 'big_south', 'sun_belt', 'maac', 'mvc',
       'aec', 'patriot', 'mw_coll', 'wcc', 'caa', 'nec', 'mid_cont',
       'mac', 'meac', 'swac', 'southland', 'wac', 'a_ten', 'cusa',
       'big_east', 'sec', 'big_twelve', 'big_west', 'mwc', 'acc',
       'big_ten', 'big_sky', 'horizon', 'pac_ten', 'summit', 'gwc',
       'pac_twelve', 'aac', 'ivy'], dtype=object)

In [46]:
data['MGameCities']

       Season  DayNum  WTeamID  LTeamID   CRType  CityID
0        2010       7     1143     1293  Regular    4027
1        2010       7     1314     1198  Regular    4061
2        2010       7     1326     1108  Regular    4080
3        2010       7     1393     1107  Regular    4340
4        2010       9     1143     1178  Regular    4027
...       ...     ...      ...      ...      ...     ...
90679    2026      93     1457     1347  Regular    4286
90680    2026      93     1459     1440  Regular    4194
90681    2026      93     1464     1236  Regular    4124
90682    2026      93     1472     1355  Regular    4046
90683    2026      93     1477     1322  Regular    4234

[90684 rows x 6 columns]