In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [9]:
df1 = pd.read_csv('march-machine-learning-mania-2026/Cities.csv')
df1.head(3)

   CityID     City State
0    4001  Abilene    TX
1    4002    Akron    OH
2    4003   Albany    NY

In [7]:
df2 = pd.read_csv('march-machine-learning-mania-2026/MSeasons.csv')
df2.head(3)

   Season     DayZero RegionW    RegionX    RegionY    RegionZ
0    1985  10/29/1984    East       West    Midwest  Southeast
1    1986  10/28/1985    East    Midwest  Southeast       West
2    1987  10/27/1986    East  Southeast    Midwest       West

In [8]:
df3 = pd.read_csv('march-machine-learning-mania-2026/MNCAATourneySeeds.csv')
df3.head(3)

   Season Seed  TeamID
0    1985  W01    1207
1    1985  W02    1210
2    1985  W03    1228

In [ ]:
df4 = pd